import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;

public class InvoiceManager {
    private ArrayList<Invoice> invoiceList;
    private ArrayList<String> customerList; 
    
    // --- NEW DIRECTORY AND FILE PATHS ---
    private final String DATA_FOLDER = "data";
    private final String FILE_NAME = "data/invoices.csv";
    private final String CUSTOMER_FILE = "data/customers.csv"; 

    public InvoiceManager() {
        invoiceList = new ArrayList<>();
        customerList = new ArrayList<>();
        
        // Ensure the 'data' folder exists before doing anything else
        File folder = new File(DATA_FOLDER);
        if (!folder.exists()) {
            folder.mkdir();
        }
        
        loadCustomers(); 
        loadInvoices();
    }

    private void loadCustomers() {
        try {
            File file = new File(CUSTOMER_FILE);
            if (!file.exists()) {
                customerList.add("");
                saveCustomers();
                return; 
            }
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String name = scanner.nextLine().trim();
                if (!name.isEmpty()) customerList.add(name);
            }
            scanner.close();
        } catch (Exception e) {
            System.out.println("Error loading customers: " + e.getMessage());
        }
    }

    private void saveCustomers() {
        try {
            FileWriter fw = new FileWriter(CUSTOMER_FILE, false);
            PrintWriter pw = new PrintWriter(fw);
            for (String customer : customerList) {
                pw.println(customer);
            }
            pw.close();
        } catch (Exception e) {
            System.out.println("Error saving customers: " + e.getMessage());
        }
    }

    public void addCustomer(String name) {
        if (!customerList.contains(name)) {
            customerList.add(name);
            saveCustomers();
        }
    }

    public ArrayList<String> getCustomers() {
        return customerList;
    }

    private void loadInvoices() {
        File file = new File(FILE_NAME);
        if (!file.exists()) return; 

        try (Scanner scanner = new Scanner(file)) {
            boolean isFirstLine = true;
            
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine().trim();
                
                // Skip completely empty lines generated by Excel
                if (line.isEmpty()) continue;
                
                // Safely skip the header row on the first pass
                if (isFirstLine) {
                    isFirstLine = false;
                    if (line.toLowerCase().contains("date") || line.toLowerCase().contains("invoice")) {
                        continue; // Skip processing the header
                    }
                }
                
                // --- Row-Specific Error Handling ---
                // If one row is broken, it won't crash the whole file
                try {
                    // Split by comma, ignoring commas inside quotes
                    String[] data = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)"); 

                    if (data.length >= 10) {
                        // Strip quotes and trim invisible spaces
                        for (int i = 0; i < data.length; i++) {
                            data[i] = data[i].replaceAll("^\"|\"$", "").trim();
                        }
                        
                        // Parse numbers safely, defaulting to 0.0 if Excel left them blank
                        double amount = data[5].isEmpty() ? 0.0 : Double.parseDouble(data[5]);
                        double amountPaid = data[6].isEmpty() ? 0.0 : Double.parseDouble(data[6]);

                        Invoice inv = new Invoice(data[0], data[1], data[2], data[3], data[4], 
                                                  amount, amountPaid, 
                                                  data[7], data[8], data[9]);
                        invoiceList.add(inv);
                    }
                } catch (Exception rowEx) {
                    // Silently skip the broken row and continue loading the rest
                    System.out.println("Skipped unreadable row: " + line);
                }
            }
        } catch (Exception e) {
            System.out.println("Error opening invoice file: " + e.getMessage());
        }
    }

    private void saveAllToFile() {
        try {
            FileWriter fw = new FileWriter(FILE_NAME, false);
            PrintWriter pw = new PrintWriter(fw);
            
            // Add the Header Row for clean Excel formatting
            pw.println("Date,Invoice ID,Job No,Customer,Description,Amount,Amount Paid,Status,Paid Date,Remark");
            
            for (Invoice inv : invoiceList) {
                // Manually formats the CSV instead of using toFileString()
                // Wraps text fields in quotes ("%s") so commas in user descriptions don't break Excel columns
                pw.println(String.format("\"%s\",\"%s\",\"%s\",\"%s\",\"%s\",%s,%s,\"%s\",\"%s\",\"%s\"", 
                    inv.getDate(), 
                    inv.getInvoiceId(), 
                    inv.getJobNo(), 
                    inv.getCustomerName(), 
                    inv.getDescription(), 
                    inv.getAmount(), 
                    inv.getAmountPaid(), 
                    inv.getStatus(), 
                    inv.getPaidDate(), 
                    inv.getRemark()
                ));
            }
            pw.close();
        } catch (Exception e) {
            System.out.println("Error saving file: " + e.getMessage());
        }
    }

    public void addNewInvoice(String date, String id, String jobNo, String customer, String desc, double amount, String remark) {
        Invoice newInv = new Invoice(date, id, jobNo, customer, desc, amount, 0.0, "Unpaid", "-", remark);
        invoiceList.add(newInv); 
        saveAllToFile();         
    }

    public void updatePayment(String targetId, double newAmountPaid, String datePaid) {
        for (Invoice inv : invoiceList) {
            if (inv.getInvoiceId().equals(targetId)) {
                inv.setAmountPaid(newAmountPaid);
                if (newAmountPaid >= inv.getAmount()) {
                    inv.setStatus("Paid");
                    inv.setPaidDate(datePaid);
                } else if (newAmountPaid > 0) {
                    inv.setStatus("Partial");
                    inv.setPaidDate(datePaid);
                } else {
                    inv.setStatus("Unpaid");
                    inv.setPaidDate("-");
                }
                saveAllToFile(); 
                break; 
            }
        }
    }

    public void updateInvoice(String oldId, String newDate, String newId, String newJobNo, String newCustomer, String newDesc, double newAmount, double newAmtPaid, String newRemark) {
        for (int i = 0; i < invoiceList.size(); i++) {
            Invoice inv = invoiceList.get(i);
            if (inv.getInvoiceId().equals(oldId)) {
                Invoice updatedInv = new Invoice(newDate, newId, newJobNo, newCustomer, newDesc, newAmount, newAmtPaid, inv.getStatus(), inv.getPaidDate(), newRemark);
                invoiceList.set(i, updatedInv); 
                updatePayment(newId, newAmtPaid, inv.getPaidDate()); 
                break;
            }
        }
    }

    public void deleteInvoice(String targetId) {
        invoiceList.removeIf(inv -> inv.getInvoiceId().equals(targetId));
        saveAllToFile();
    }
    
    public ArrayList<Invoice> getAllInvoices() {
        return invoiceList;
    }
}
